const { contextBridge, ipcRenderer } = require('electron')
const path = require('path')

const webviewPreload = path.join(__dirname, 'webview-preload.js')

contextBridge.exposeInMainWorld('onyx', {
  minimize: () => ipcRenderer.send('win:minimize'),
  maximize: () => ipcRenderer.send('win:maximize'),
  close: () => ipcRenderer.send('win:close'),
  toggleFullscreen: () => ipcRenderer.send('win:fullscreen'),
  readData: (f, fb) => ipcRenderer.invoke('data:read', f, fb),
  writeData: (f, d) => ipcRenderer.invoke('data:write', f, d),
  openDir: () => ipcRenderer.invoke('dialog:dir'),
  openExternal: (u) => ipcRenderer.invoke('shell:external', u),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  showInFolder: (p) => ipcRenderer.invoke('shell:showInFolder', p),
  getWebviewPreload: () => webviewPreload,
  setDefaultBrowser: () => ipcRenderer.invoke('browser:setDefault'),
  openDefaultApps: () => ipcRenderer.invoke('browser:openDefaultApps'),
  getBrowserPath: () => ipcRenderer.invoke('browser:getPath'),
  listExtensions: () => ipcRenderer.invoke('ext:list'),
  openExtensionsFolder: () => ipcRenderer.invoke('ext:openFolder'),
  cancelDownload: (id) => ipcRenderer.send('download:cancel', id),
  pauseDownload: (id) => ipcRenderer.send('download:pause', id),
  resumeDownload: (id) => ipcRenderer.send('download:resume', id),
  saveShot: (buf, name) => ipcRenderer.invoke('shot:save', buf, name),
  copyImage: (buf) => ipcRenderer.invoke('shot:copy', buf),
  pipOpen: (url, title) => ipcRenderer.invoke('pip:open', url, title),
  setAdblock: (on) => ipcRenderer.send('adblock:set', on),
  setPrivacy: (cfg) => ipcRenderer.send('privacy:set', cfg),
  setCookieTtl: (days) => ipcRenderer.send('privacy:ttl', days),
  clearCache: () => ipcRenderer.invoke('privacy:clearCache'),
  getCookies: () => ipcRenderer.invoke('privacy:cookies'),
  clearSiteData: (origin) => ipcRenderer.invoke('privacy:clearSite', origin),
  clearAllCookies: () => ipcRenderer.invoke('privacy:clearAllCookies'),
  readClipboard: () => ipcRenderer.invoke('clipboard:read'),
  writeClipboard: (txt) => ipcRenderer.invoke('clipboard:write', txt),
  saveBackup: (name, content) => ipcRenderer.invoke('data:saveBackup', name, content),
  loadBackup: () => ipcRenderer.invoke('data:loadBackup'),
  onDownloadStart: (cb) => ipcRenderer.on('download:start', (_, info) => cb(info)),
  onDownloadProgress: (cb) => ipcRenderer.on('download:progress', (_, data) => cb(data)),
  onDownloadDone: (cb) => ipcRenderer.on('download:done', (_, data) => cb(data)),
})
