import type { ThemePreset, ThemeColors } from './types'

export type LayoutPosition = 'top' | 'bottom'
export type SidebarSide = 'left' | 'right'

export interface UIPreset {
  id: string
  name: string
  description: string
  author: string
  accent: string
  bg: string
  theme: ThemePreset
  customColors?: ThemeColors
  tabShape: 'square' | 'rounded' | 'pill' | 'trapezoid' | 'yandex' | 'wave'
  fontFamily: string
  fontSize: number
  tabBarHeight: number
  statusBarHeight: number
  titlebarHeight: number
  borderRadius: number
  transitionSpeed: number
  tabOpacity: number
  ntpLayout: 'default' | 'minimal' | 'centered' | 'zen' | 'gradient'
  tabBarPosition: LayoutPosition
  statusBarPosition: LayoutPosition
  sidebarPosition: SidebarSide
  sidebarWidth: number
  workspacePosition: 'top' | 'bottom'
  showTabBar: boolean
  showStatusBar: boolean
  workspaceShow: boolean
  zenMode: boolean
}

export const BUILT_IN_PRESETS: UIPreset[] = [
  // ─── Classic ──────────────────────────────────────
  {
    id: 'vox-classic',
    name: 'Vox Classic',
    description: 'The default. Tokyo Night, rounded tabs, balanced.',
    author: 'Vox',
    accent: '#7aa2f7',
    bg: '#1a1b26',
    theme: 'tokyo-night',
    tabShape: 'rounded',
    fontFamily: "'Consolas', 'SF Mono', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'vox-classic-dark',
    name: 'Vox Classic Dark',
    description: 'Same layout, deeper colors. Gruvbox warmth.',
    author: 'Vox',
    accent: '#458588',
    bg: '#282828',
    theme: 'gruvbox',
    tabShape: 'rounded',
    fontFamily: "'Consolas', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Zen / Minimal ────────────────────────────────
  {
    id: 'zen-minimal',
    name: 'Zen Minimal',
    description: 'Nord. Pill tabs. No status bar. Centered NTP.',
    author: 'Vox',
    accent: '#88c0d0',
    bg: '#2e3440',
    theme: 'nord',
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    tabBarHeight: 30,
    statusBarHeight: 24,
    titlebarHeight: 2,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 0.85,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'midnight-zen',
    name: 'Midnight Zen',
    description: 'Full zen mode. Sidebar tabs, gradient NTP, nothing else.',
    author: 'Vox',
    accent: '#bb9af7',
    bg: '#1a1b26',
    theme: 'tokyo-night',
    tabShape: 'rounded',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 0,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 280,
    workspacePosition: 'top',
    showTabBar: false,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: true,
  },
  {
    id: 'ultra-minimal',
    name: 'Ultra Minimal',
    description: 'Almost nothing visible. 2px titlebar, tiny tabs, right sidebar.',
    author: 'Vox',
    accent: '#565f89',
    bg: '#16161e',
    theme: 'custom',
    customColors: {
      bg: '#16161e', bgDim: '#111119', bgLight: '#1e1e2e',
      fg: '#a9b1d6', fgDim: '#444b6a', border: '#1e1e2e',
      accent: '#565f89', green: '#9ece6a', red: '#f7768e',
      orange: '#ff9e64', cyan: '#7dcfff', purple: '#bb9af7',
    },
    tabShape: 'pill',
    fontFamily: "system-ui, sans-serif",
    fontSize: 12,
    tabBarHeight: 26,
    statusBarHeight: 20,
    titlebarHeight: 2,
    borderRadius: 10,
    transitionSpeed: 300,
    tabOpacity: 0.7,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 260,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'flatland',
    name: 'Flatland',
    description: 'Completely flat. No border radius. Tabs at bottom, sidebar right.',
    author: 'Vox',
    accent: '#88c0d0',
    bg: '#2e3440',
    theme: 'nord',
    tabShape: 'square',
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Browser clones ───────────────────────────────
  {
    id: 'chrome-cloned',
    name: 'Chrome Style',
    description: 'Looks like Chrome. Tabs on top, blue accent, centered NTP.',
    author: 'Vox',
    accent: '#4285f4',
    bg: '#202124',
    theme: 'custom',
    customColors: {
      bg: '#202124', bgDim: '#17181a', bgLight: '#292a2d',
      fg: '#e8eaed', fgDim: '#9aa0a6', border: '#3c4043',
      accent: '#4285f4', green: '#34a853', red: '#ea4335',
      orange: '#fbbc04', cyan: '#00bcd4', purple: '#a142f4',
    },
    tabShape: 'rounded',
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 24,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'firefox-cloned',
    name: 'Firefox Style',
    description: 'Firefox Proton look. Tabs on top, orange accent.',
    author: 'Vox',
    accent: '#ff7139',
    bg: '#1c1b22',
    theme: 'custom',
    customColors: {
      bg: '#1c1b22', bgDim: '#15141a', bgLight: '#2b2a33',
      fg: '#fbfbfe', fgDim: '#8f8f9d', border: '#3b3a44',
      accent: '#ff7139', green: '#058b00', red: '#ff4f5e',
      orange: '#ff9f00', cyan: '#00c8ff', purple: '#bf5af2',
    },
    tabShape: 'square',
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'edge-cloned',
    name: 'Edge Style',
    description: 'Microsoft Edge. Tabs on top, cool blue-grey.',
    author: 'Vox',
    accent: '#0078d4',
    bg: '#1f1f1f',
    theme: 'custom',
    customColors: {
      bg: '#1f1f1f', bgDim: '#161616', bgLight: '#2d2d2d',
      fg: '#ffffff', fgDim: '#999999', border: '#404040',
      accent: '#0078d4', green: '#16c60c', red: '#e81123',
      orange: '#f7630c', cyan: '#00b7c3', purple: '#8764b8',
    },
    tabShape: 'pill',
    fontFamily: "system-ui, 'Segoe UI', sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 26,
    titlebarHeight: 6,
    borderRadius: 8,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'opera-cloned',
    name: 'Opera Style',
    description: 'Opera GX vibes. Tabs top, red-black, sidebar right.',
    author: 'Vox',
    accent: '#ff1b2d',
    bg: '#121212',
    theme: 'custom',
    customColors: {
      bg: '#121212', bgDim: '#0a0a0a', bgLight: '#1e1e1e',
      fg: '#ffffff', fgDim: '#7a7a7a', border: '#2a2a2a',
      accent: '#ff1b2d', green: '#00e676', red: '#ff1744',
      orange: '#ff9100', cyan: '#00e5ff', purple: '#d500f9',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Consolas', monospace",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 0,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'yandex-cloned',
    name: 'Yandex Style',
    description: 'Yandex Browser. Tabs on top, bright accent.',
    author: 'Vox',
    accent: '#fc3f1d',
    bg: '#191919',
    theme: 'custom',
    customColors: {
      bg: '#191919', bgDim: '#111111', bgLight: '#262626',
      fg: '#ffffff', fgDim: '#999999', border: '#333333',
      accent: '#fc3f1d', green: '#3fcc2f', red: '#ff3333',
      orange: '#ff9900', cyan: '#33ccff', purple: '#9966ff',
    },
    tabShape: 'yandex',
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 3,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'arc-cloned',
    name: 'Arc Style',
    description: 'Arc Browser look. Sidebar tabs, no tab bar, pill shapes.',
    author: 'Vox',
    accent: '#6e56cf',
    bg: '#1a1a2e',
    theme: 'custom',
    customColors: {
      bg: '#1a1a2e', bgDim: '#12121f', bgLight: '#252540',
      fg: '#e0def4', fgDim: '#6e6e8a', border: '#2a2a45',
      accent: '#6e56cf', green: '#56d364', red: '#f85149',
      orange: '#d29922', cyan: '#39c5cf', purple: '#bc8cff',
    },
    tabShape: 'pill',
    fontFamily: "'SF Mono', 'Fira Code', monospace",
    fontSize: 12,
    tabBarHeight: 32,
    statusBarHeight: 0,
    titlebarHeight: 0,
    borderRadius: 12,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 280,
    workspacePosition: 'top',
    showTabBar: false,
    showStatusBar: false,
    workspaceShow: true,
    zenMode: true,
  },

  // ─── Color themes ─────────────────────────────────
  {
    id: 'dracula-vampire',
    name: 'Dracula Vampire',
    description: 'Dark dramatic. Dracula + trapezoid tabs. Workspaces at bottom.',
    author: 'Vox',
    accent: '#bd93f9',
    bg: '#282a36',
    theme: 'dracula',
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  // ─── Trapezoid Bottom collection ──────────────────
  {
    id: 'crimson-trap',
    name: 'Crimson Trap',
    description: 'Blood red on void. Trapezoid bottom tabs. Dark and sharp.',
    author: 'Vox',
    accent: '#ff1744',
    bg: '#1a0a0a',
    theme: 'custom',
    customColors: {
      bg: '#1a0a0a', bgDim: '#120606', bgLight: '#2a1010',
      fg: '#ffcdd2', fgDim: '#b71c1c', border: '#3d1111',
      accent: '#ff1744', green: '#69f0ae', red: '#ff1744',
      orange: '#ff6e40', cyan: '#84ffff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'emerald-trap',
    name: 'Emerald Trap',
    description: 'Deep green matrix. Trapezoid bottom tabs. Cool and focused.',
    author: 'Vox',
    accent: '#00e676',
    bg: '#0a1a0e',
    theme: 'custom',
    customColors: {
      bg: '#0a1a0e', bgDim: '#061208', bgLight: '#142618',
      fg: '#c8e6c9', fgDim: '#2e7d32', border: '#1b5e20',
      accent: '#00e676', green: '#00e676', red: '#ff5252',
      orange: '#ffab40', cyan: '#18ffff', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'ocean-trap',
    name: 'Ocean Trap',
    description: 'Deep ocean blue. Trapezoid bottom tabs. Calm and deep.',
    author: 'Vox',
    accent: '#448aff',
    bg: '#0a1525',
    theme: 'custom',
    customColors: {
      bg: '#0a1525', bgDim: '#060f1c', bgLight: '#122035',
      fg: '#bbdefb', fgDim: '#1565c0', border: '#1a3a5c',
      accent: '#448aff', green: '#69f0ae', red: '#ff5252',
      orange: '#ffab40', cyan: '#00e5ff', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'sunset-trap',
    name: 'Sunset Trap',
    description: 'Warm sunset orange. Trapezoid bottom tabs. Cozy and rich.',
    author: 'Vox',
    accent: '#ff9100',
    bg: '#1a0e00',
    theme: 'custom',
    customColors: {
      bg: '#1a0e00', bgDim: '#120a00', bgLight: '#2a1800',
      fg: '#ffe0b2', fgDim: '#e65100', border: '#4e2600',
      accent: '#ff9100', green: '#69f0ae', red: '#ff1744',
      orange: '#ff9100', cyan: '#84ffff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'arctic-trap',
    name: 'Arctic Trap',
    description: 'Ice cold blue-white. Trapezoid bottom tabs. Clean and crisp.',
    author: 'Vox',
    accent: '#80d8ff',
    bg: '#0e1a24',
    theme: 'custom',
    customColors: {
      bg: '#0e1a24', bgDim: '#09131b', bgLight: '#162636',
      fg: '#e1f5fe', fgDim: '#0288d1', border: '#1a3a5c',
      accent: '#80d8ff', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffb74d', cyan: '#00e5ff', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'lavender-trap',
    name: 'Lavender Trap',
    description: 'Soft purple haze. Trapezoid bottom tabs. Dreamy and mellow.',
    author: 'Vox',
    accent: '#b388ff',
    bg: '#140a1e',
    theme: 'custom',
    customColors: {
      bg: '#140a1e', bgDim: '#0e0616', bgLight: '#1e1230',
      fg: '#e1bee7', fgDim: '#7b1fa2', border: '#311b52',
      accent: '#b388ff', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffcc80', cyan: '#80deea', purple: '#ce93d8',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'amber-trap',
    name: 'Amber Trap',
    description: 'Golden amber glow. Trapezoid bottom tabs. Warm and regal.',
    author: 'Vox',
    accent: '#ffc400',
    bg: '#1a1400',
    theme: 'custom',
    customColors: {
      bg: '#1a1400', bgDim: '#120e00', bgLight: '#2a2000',
      fg: '#fff8e1', fgDim: '#f57f17', border: '#4e3c00',
      accent: '#ffc400', green: '#69f0ae', red: '#ff1744',
      orange: '#ffab00', cyan: '#84ffff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'neon-pink-trap',
    name: 'Neon Pink Trap',
    description: 'Hot neon pink. Trapezoid bottom tabs. Bold and electric.',
    author: 'Vox',
    accent: '#ff4081',
    bg: '#180a14',
    theme: 'custom',
    customColors: {
      bg: '#180a14', bgDim: '#12060e', bgLight: '#281220',
      fg: '#fce4ec', fgDim: '#c2185b', border: '#4a1230',
      accent: '#ff4081', green: '#69f0ae', red: '#ff1744',
      orange: '#ff6e40', cyan: '#18ffff', purple: '#f50057',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'cyber-yellow-trap',
    name: 'Cyber Yellow Trap',
    description: 'Electric yellow on black. Trapezoid bottom tabs. Cyberpunk edge.',
    author: 'Vox',
    accent: '#ffea00',
    bg: '#121200',
    theme: 'custom',
    customColors: {
      bg: '#121200', bgDim: '#0c0c00', bgLight: '#1e1e00',
      fg: '#fffde7', fgDim: '#9e9d24', border: '#3d3d00',
      accent: '#ffea00', green: '#69f0ae', red: '#ff1744',
      orange: '#ffab00', cyan: '#00e5ff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'teal-trap',
    name: 'Teal Trap',
    description: 'Deep teal. Trapezoid bottom tabs. Balanced and smooth.',
    author: 'Vox',
    accent: '#1de9b6',
    bg: '#0a1a18',
    theme: 'custom',
    customColors: {
      bg: '#0a1a18', bgDim: '#061210', bgLight: '#142622',
      fg: '#b2dfdb', fgDim: '#00897b', border: '#004d40',
      accent: '#1de9b6', green: '#69f0ae', red: '#ff5252',
      orange: '#ffab40', cyan: '#00e5ff', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'coral-trap',
    name: 'Coral Trap',
    description: 'Soft coral pink. Trapezoid bottom tabs. Warm and inviting.',
    author: 'Vox',
    accent: '#ff8a80',
    bg: '#1a0e10',
    theme: 'custom',
    customColors: {
      bg: '#1a0e10', bgDim: '#12090b', bgLight: '#2a1818',
      fg: '#fce4ec', fgDim: '#e57373', border: '#4e2028',
      accent: '#ff8a80', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffab91', cyan: '#80deea', purple: '#ce93d8',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'wine-trap',
    name: 'Wine Trap',
    description: 'Deep burgundy wine. Trapezoid bottom tabs. Sophisticated.',
    author: 'Vox',
    accent: '#c62828',
    bg: '#1a0808',
    theme: 'custom',
    customColors: {
      bg: '#1a0808', bgDim: '#120505', bgLight: '#2a1010',
      fg: '#f8bbd0', fgDim: '#880e4f', border: '#4a0e1e',
      accent: '#c62828', green: '#69f0ae', red: '#c62828',
      orange: '#ff6e40', cyan: '#84ffff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'moss-trap',
    name: 'Moss Trap',
    description: 'Earthy moss green. Trapezoid bottom tabs. Organic and grounded.',
    author: 'Vox',
    accent: '#8bc34a',
    bg: '#121a08',
    theme: 'custom',
    customColors: {
      bg: '#121a08', bgDim: '#0c1205', bgLight: '#1e2a10',
      fg: '#dcedc8', fgDim: '#558b2f', border: '#33691e',
      accent: '#8bc34a', green: '#8bc34a', red: '#ef5350',
      orange: '#ffb74d', cyan: '#80deea', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'midnight-trap',
    name: 'Midnight Trap',
    description: 'Pure midnight black. Trapezoid bottom tabs. Shadow mode.',
    author: 'Vox',
    accent: '#607d8b',
    bg: '#080a0c',
    theme: 'custom',
    customColors: {
      bg: '#080a0c', bgDim: '#040506', bgLight: '#101418',
      fg: '#b0bec5', fgDim: '#455a64', border: '#1c2630',
      accent: '#607d8b', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffab91', cyan: '#80deea', purple: '#b39ddb',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'rose-trap',
    name: 'Rose Trap',
    description: 'Deep rose pink. Trapezoid bottom tabs. Elegant and bold.',
    author: 'Vox',
    accent: '#e91e63',
    bg: '#1a0810',
    theme: 'custom',
    customColors: {
      bg: '#1a0810', bgDim: '#12050b', bgLight: '#2a101a',
      fg: '#fce4ec', fgDim: '#ad1457', border: '#4a0e28',
      accent: '#e91e63', green: '#69f0ae', red: '#e91e63',
      orange: '#ffab40', cyan: '#00e5ff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'copper-trap',
    name: 'Copper Trap',
    description: 'Burnished copper. Trapezoid bottom tabs. Industrial warmth.',
    author: 'Vox',
    accent: '#bf6830',
    bg: '#1a1008',
    theme: 'custom',
    customColors: {
      bg: '#1a1008', bgDim: '#120b05', bgLight: '#2a1a10',
      fg: '#ffe0b2', fgDim: '#a1887f', border: '#5d4037',
      accent: '#bf6830', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffab40', cyan: '#80deea', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'sapphire-trap',
    name: 'Sapphire Trap',
    description: 'Rich sapphire blue. Trapezoid bottom tabs. Royal and deep.',
    author: 'Vox',
    accent: '#2979ff',
    bg: '#080c1a',
    theme: 'custom',
    customColors: {
      bg: '#080c1a', bgDim: '#050812', bgLight: '#101830',
      fg: '#bbdefb', fgDim: '#1565c0', border: '#0d47a1',
      accent: '#2979ff', green: '#69f0ae', red: '#ff5252',
      orange: '#ffab40', cyan: '#40c4ff', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'peach-trap',
    name: 'Peach Trap',
    description: 'Soft peach warm. Trapezoid bottom tabs. Gentle and cozy.',
    author: 'Vox',
    accent: '#ffab91',
    bg: '#1a100c',
    theme: 'custom',
    customColors: {
      bg: '#1a100c', bgDim: '#120b08', bgLight: '#2a1a14',
      fg: '#fbe9e7', fgDim: '#a1887f', border: '#5d4037',
      accent: '#ffab91', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffb74d', cyan: '#80deea', purple: '#ce93d8',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'jade-trap',
    name: 'Jade Trap',
    description: 'Precious jade green. Trapezoid bottom tabs. Lucky and serene.',
    author: 'Vox',
    accent: '#00c853',
    bg: '#081810',
    theme: 'custom',
    customColors: {
      bg: '#081810', bgDim: '#05120b', bgLight: '#102818',
      fg: '#c8e6c9', fgDim: '#2e7d32', border: '#1b5e20',
      accent: '#00c853', green: '#00c853', red: '#ff5252',
      orange: '#ffab40', cyan: '#18ffff', purple: '#b388ff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'storm-trap',
    name: 'Storm Trap',
    description: 'Thunderstorm gray-blue. Trapezoid bottom tabs. Moody and atmospheric.',
    author: 'Vox',
    accent: '#5c6bc0',
    bg: '#0e1018',
    theme: 'custom',
    customColors: {
      bg: '#0e1018', bgDim: '#090b10', bgLight: '#181c28',
      fg: '#c5cae9', fgDim: '#3f51b5', border: '#1a237e',
      accent: '#5c6bc0', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffab91', cyan: '#80deea', purple: '#9575cd',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'mango-trap',
    name: 'Mango Trap',
    description: 'Tropical mango. Trapezoid bottom tabs. Vibrant and juicy.',
    author: 'Vox',
    accent: '#ff6f00',
    bg: '#1a1000',
    theme: 'custom',
    customColors: {
      bg: '#1a1000', bgDim: '#120b00', bgLight: '#2a1a00',
      fg: '#fff3e0', fgDim: '#e65100', border: '#bf360c',
      accent: '#ff6f00', green: '#69f0ae', red: '#ff1744',
      orange: '#ff6f00', cyan: '#84ffff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'obsidian-trap',
    name: 'Obsidian Trap',
    description: 'Volcanic obsidian. Trapezoid bottom tabs. Dark and powerful.',
    author: 'Vox',
    accent: '#ff6e40',
    bg: '#0c0a0a',
    theme: 'custom',
    customColors: {
      bg: '#0c0a0a', bgDim: '#080606', bgLight: '#181414',
      fg: '#e0e0e0', fgDim: '#616161', border: '#2a2424',
      accent: '#ff6e40', green: '#69f0ae', red: '#ff1744',
      orange: '#ff6e40', cyan: '#84ffff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'slate-trap',
    name: 'Slate Trap',
    description: 'Pure gray slate. Trapezoid bottom tabs. Ultra minimal monochrome.',
    author: 'Vox',
    accent: '#90a4ae',
    bg: '#1a1e22',
    theme: 'custom',
    customColors: {
      bg: '#1a1e22', bgDim: '#12151a', bgLight: '#262b30',
      fg: '#eceff1', fgDim: '#546e7a', border: '#37474f',
      accent: '#90a4ae', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffab91', cyan: '#80deea', purple: '#b39ddb',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'violet-trap',
    name: 'Violet Trap',
    description: 'Deep violet. Trapezoid bottom tabs. Rich and intense.',
    author: 'Vox',
    accent: '#7c4dff',
    bg: '#12081e',
    theme: 'custom',
    customColors: {
      bg: '#12081e', bgDim: '#0c0516', bgLight: '#1c1030',
      fg: '#e8daef', fgDim: '#6a1b9a', border: '#380e60',
      accent: '#7c4dff', green: '#69f0ae', red: '#ff1744',
      orange: '#ffab40', cyan: '#00e5ff', purple: '#7c4dff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'solarized-ink',
    name: 'Solarized Ink',
    description: 'Warm Solarized Dark. Wave tabs. Sidebar right.',
    author: 'Vox',
    accent: '#268bd2',
    bg: '#002b36',
    theme: 'solarized',
    tabShape: 'wave',
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 15,
    tabBarHeight: 38,
    statusBarHeight: 30,
    titlebarHeight: 8,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 360,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'catppuccin-dream',
    name: 'Catppuccin Dream',
    description: 'Soft pastels. Catppuccin Mocha. Smooth & gentle.',
    author: 'Vox',
    accent: '#89b4fa',
    bg: '#1e1e2e',
    theme: 'catppuccin',
    tabShape: 'pill',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 250,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    description: 'Monokai. Square tabs. Tabs at bottom. Retro coder.',
    author: 'Vox',
    accent: '#a6e22e',
    bg: '#272822',
    theme: 'monokai',
    tabShape: 'square',
    fontFamily: "'Consolas', monospace",
    fontSize: 14,
    tabBarHeight: 36,
    statusBarHeight: 30,
    titlebarHeight: 10,
    borderRadius: 0,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'ayu-mirage',
    name: 'Ayu Mirage',
    description: 'Sleek Ayu Dark. Rounded tabs. Centered NTP.',
    author: 'Vox',
    accent: '#36a3d9',
    bg: '#0f1419',
    theme: 'ayu',
    tabShape: 'rounded',
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 5,
    transitionSpeed: 180,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'one-dark-atom',
    name: 'One Dark Atom',
    description: 'Atom editor vibes. One Dark. Wave tabs at bottom.',
    author: 'Vox',
    accent: '#61afef',
    bg: '#282c34',
    theme: 'one-dark',
    tabShape: 'wave',
    fontFamily: "'Fira Code', 'Source Code Pro', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Light themes ─────────────────────────────────
  {
    id: 'github-coder',
    name: 'GitHub Coder',
    description: 'GitHub Light. Tabs on top. Clean daytime coding.',
    author: 'Vox',
    accent: '#0969da',
    bg: '#ffffff',
    theme: 'github-light',
    tabShape: 'square',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    tabBarHeight: 30,
    statusBarHeight: 24,
    titlebarHeight: 2,
    borderRadius: 2,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'latte-latte',
    name: 'Catppuccin Latte',
    description: 'Soft light. Catppuccin Latte. Tabs on top.',
    author: 'Vox',
    accent: '#1e66f5',
    bg: '#eff1f5',
    theme: 'catppuccin-latte',
    tabShape: 'pill',
    fontFamily: "'SF Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'tokyo-day',
    name: 'Tokyo Day',
    description: 'Tokyo Day light theme. Tabs on top. Clean & modern.',
    author: 'Vox',
    accent: '#2e7de9',
    bg: '#e1e2e7',
    theme: 'tokyo-day',
    tabShape: 'rounded',
    fontFamily: "system-ui, sans-serif",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 6,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    description: 'Solarized Light. Wave tabs. Sidebar right.',
    author: 'Vox',
    accent: '#268bd2',
    bg: '#fdf6e3',
    theme: 'solarized-light',
    tabShape: 'wave',
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 14,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 180,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'nord-light',
    name: 'Nord Light',
    description: 'Nord Light. Tabs on top. Clean, calm, readable.',
    author: 'Vox',
    accent: '#5e81ac',
    bg: '#eceff4',
    theme: 'nord-light',
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Extreme / Experimental ───────────────────────
  {
    id: 'terminal-green',
    name: 'Terminal Green',
    description: 'Matrix vibes. Green on black. Tabs bottom, sidebar right.',
    author: 'Vox',
    accent: '#00ff41',
    bg: '#0d0208',
    theme: 'custom',
    customColors: {
      bg: '#0d0208', bgDim: '#000000', bgLight: '#003b00',
      fg: '#00ff41', fgDim: '#007a1c', border: '#003b00',
      accent: '#00ff41', green: '#00ff41', red: '#ff0000',
      orange: '#ff8c00', cyan: '#00ffff', purple: '#ff00ff',
    },
    tabShape: 'square',
    fontFamily: "'Consolas', 'Courier New', monospace",
    fontSize: 13,
    tabBarHeight: 28,
    statusBarHeight: 22,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 50,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'bottom',
    statusBarPosition: 'top',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'synthwave-neon',
    name: 'Synthwave Neon',
    description: 'Retro-futuristic. Tabs bottom. Neon pink/cyan, sidebar right.',
    author: 'Vox',
    accent: '#f72585',
    bg: '#0f0e17',
    theme: 'custom',
    customColors: {
      bg: '#0f0e17', bgDim: '#08070d', bgLight: '#1a1928',
      fg: '#fffffe', fgDim: '#72757e', border: '#2e2d3d',
      accent: '#f72585', green: '#4cc9f0', red: '#ff006e',
      orange: '#fb5607', cyan: '#4cc9f0', purple: '#7209b7',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'rose-pine',
    name: 'Rose Pine',
    description: 'Rose Pine palette. Soft & muted. Pill tabs on top.',
    author: 'Vox',
    accent: '#c4a7e7',
    bg: '#191724',
    theme: 'custom',
    customColors: {
      bg: '#191724', bgDim: '#111019', bgLight: '#26233a',
      fg: '#e0def4', fgDim: '#6e6a86', border: '#26233a',
      accent: '#c4a7e7', green: '#9ccfd8', red: '#eb6f92',
      orange: '#ea9a97', cyan: '#9ccfd8', purple: '#c4a7e7',
    },
    tabShape: 'pill',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 10,
    transitionSpeed: 250,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'nord-dark-max',
    name: 'Nord Max',
    description: 'Nord Dark, maximum size. Large font, tall bars.',
    author: 'Vox',
    accent: '#88c0d0',
    bg: '#2e3440',
    theme: 'nord',
    tabShape: 'square',
    fontFamily: "'Consolas', monospace",
    fontSize: 16,
    tabBarHeight: 44,
    statusBarHeight: 34,
    titlebarHeight: 12,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 360,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'compact-rocket',
    name: 'Compact Rocket',
    description: 'Tiny & fast. 24px tabs, compact sidebar.',
    author: 'Vox',
    accent: '#7dcfff',
    bg: '#1a1b26',
    theme: 'tokyo-night',
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    tabBarHeight: 24,
    statusBarHeight: 20,
    titlebarHeight: 2,
    borderRadius: 4,
    transitionSpeed: 80,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 280,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'gruvbox-retro',
    name: 'Gruvbox Retro',
    description: 'Gruvbox warmth. Tabs bottom. Sidebar right. Zero radius.',
    author: 'Vox',
    accent: '#d79921',
    bg: '#282828',
    theme: 'gruvbox',
    tabShape: 'square',
    fontFamily: "'Consolas', monospace",
    fontSize: 14,
    tabBarHeight: 36,
    statusBarHeight: 30,
    titlebarHeight: 10,
    borderRadius: 0,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    description: 'Very dark blue. Tabs top. Sidebar right. Max immersion.',
    author: 'Vox',
    accent: '#3b4252',
    bg: '#0b0e14',
    theme: 'custom',
    customColors: {
      bg: '#0b0e14', bgDim: '#060810', bgLight: '#141820',
      fg: '#8892b0', fgDim: '#2e3450', border: '#141820',
      accent: '#64ffda', green: '#64ffda', red: '#ff5370',
      orange: '#f78c6c', cyan: '#89ddff', purple: '#c792ea',
    },
    tabShape: 'rounded',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 30,
    statusBarHeight: 22,
    titlebarHeight: 2,
    borderRadius: 3,
    transitionSpeed: 300,
    tabOpacity: 0.8,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'material-dark',
    name: 'Material Dark',
    description: 'Google Material Design. Tabs top. Blue accent.',
    author: 'Vox',
    accent: '#82b1ff',
    bg: '#263238',
    theme: 'custom',
    customColors: {
      bg: '#263238', bgDim: '#1c2529', bgLight: '#37474f',
      fg: '#eeffff', fgDim: '#546e7a', border: '#37474f',
      accent: '#82b1ff', green: '#c3e88d', red: '#ff5370',
      orange: '#f78c6c', cyan: '#89ddff', purple: '#c792ea',
    },
    tabShape: 'rounded',
    fontFamily: "'Roboto Mono', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 6,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── New wave ─────────────────────────────────────
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Hot pink + cyan on void black. Wave tabs. Aggressive.',
    author: 'Vox',
    accent: '#ff2a6d',
    bg: '#0d0221',
    theme: 'custom',
    customColors: {
      bg: '#0d0221', bgDim: '#080118', bgLight: '#190535',
      fg: '#f0f0f0', fgDim: '#5c2d82', border: '#1f0a47',
      accent: '#ff2a6d', green: '#05ffa1', red: '#ff2a6d',
      orange: '#ff6e27', cyan: '#05ffa1', purple: '#d300c5',
    },
    tabShape: 'wave',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 2,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    description: 'Northern lights. Gradient greens + purples. Rounded tabs.',
    author: 'Vox',
    accent: '#72f1b8',
    bg: '#0a0e1a',
    theme: 'custom',
    customColors: {
      bg: '#0a0e1a', bgDim: '#060a12', bgLight: '#121a2e',
      fg: '#c8d6e5', fgDim: '#4a5568', border: '#1a2540',
      accent: '#72f1b8', green: '#72f1b8', red: '#ff6b9d',
      orange: '#ffa726', cyan: '#64ffda', purple: '#b388ff',
    },
    tabShape: 'rounded',
    fontFamily: "'Fira Code', monospace",
    fontSize: 12,
    tabBarHeight: 34,
    statusBarHeight: 26,
    titlebarHeight: 2,
    borderRadius: 8,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'sunset-blvd',
    name: 'Sunset Boulevard',
    description: 'Warm sunset gradient. Amber tabs. Nostalgic.',
    author: 'Vox',
    accent: '#ff9100',
    bg: '#1a0a00',
    theme: 'custom',
    customColors: {
      bg: '#1a0a00', bgDim: '#120700', bgLight: '#2a1400',
      fg: '#ffe0b2', fgDim: '#8d6e63', border: '#3e2200',
      accent: '#ff9100', green: '#66bb6a', red: '#ef5350',
      orange: '#ff9100', cyan: '#4dd0e1', purple: '#ce93d8',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'ocean-depths',
    name: 'Ocean Depths',
    description: 'Deep sea blues. Pill tabs. Calm and focused.',
    author: 'Vox',
    accent: '#00bcd4',
    bg: '#001f3f',
    theme: 'custom',
    customColors: {
      bg: '#001f3f', bgDim: '#001529', bgLight: '#003366',
      fg: '#b3e5fc', fgDim: '#4fc3f7', border: '#004080',
      accent: '#00bcd4', green: '#69f0ae', red: '#ff5252',
      orange: '#ffab40', cyan: '#00e5ff', purple: '#b388ff',
    },
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    tabBarHeight: 30,
    statusBarHeight: 26,
    titlebarHeight: 2,
    borderRadius: 10,
    transitionSpeed: 200,
    tabOpacity: 0.85,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    description: 'Soft purples. Rounded tabs. Gentle on the eyes.',
    author: 'Vox',
    accent: '#b39ddb',
    bg: '#1a1228',
    theme: 'custom',
    customColors: {
      bg: '#1a1228', bgDim: '#130d1f', bgLight: '#251c38',
      fg: '#e1bee7', fgDim: '#7e57c2', border: '#2d1f4e',
      accent: '#b39ddb', green: '#a5d6a7', red: '#ef9a9a',
      orange: '#ffcc80', cyan: '#80deea', purple: '#ce93d8',
    },
    tabShape: 'rounded',
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'bottom',
    statusBarPosition: 'top',
    sidebarPosition: 'left',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'matrix-rain',
    name: 'Matrix Rain',
    description: 'Classic green on black. Square tabs. Hacker vibes.',
    author: 'Vox',
    accent: '#00ff41',
    bg: '#0a0a0a',
    theme: 'custom',
    customColors: {
      bg: '#0a0a0a', bgDim: '#050505', bgLight: '#141414',
      fg: '#00ff41', fgDim: '#007a1a', border: '#1a1a1a',
      accent: '#00ff41', green: '#00ff41', red: '#ff0000',
      orange: '#ff8800', cyan: '#00ffff', purple: '#00ff88',
    },
    tabShape: 'square',
    fontFamily: "'Share Tech Mono', 'Courier New', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 80,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    description: 'Sakura pink. Soft rounded tabs. Zen Japanese aesthetic.',
    author: 'Vox',
    accent: '#f48fb1',
    bg: '#1a0a10',
    theme: 'custom',
    customColors: {
      bg: '#1a0a10', bgDim: '#12070b', bgLight: '#2a1018',
      fg: '#fce4ec', fgDim: '#8d6e63', border: '#3d1522',
      accent: '#f48fb1', green: '#a5d6a7', red: '#ef5350',
      orange: '#ffab91', cyan: '#80cbc4', purple: '#ce93d8',
    },
    tabShape: 'rounded',
    fontFamily: "'Zen Kaku Gothic New', sans-serif",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 26,
    titlebarHeight: 2,
    borderRadius: 10,
    transitionSpeed: 250,
    tabOpacity: 0.9,
    ntpLayout: 'zen',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 280,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'ember-glow',
    name: 'Ember Glow',
    description: 'Deep reds + ember orange. Trapezoid tabs. Warm and intense.',
    author: 'Vox',
    accent: '#ff6d00',
    bg: '#1a0800',
    theme: 'custom',
    customColors: {
      bg: '#1a0800', bgDim: '#120500', bgLight: '#2a1000',
      fg: '#ffe0b2', fgDim: '#bf360c', border: '#4e1c00',
      accent: '#ff6d00', green: '#69f0ae', red: '#ff1744',
      orange: '#ff9100', cyan: '#40c4ff', purple: '#ea80fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'top',
    statusBarPosition: 'top',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'forest-whisper',
    name: 'Forest Whisper',
    description: 'Deep forest green. Pill tabs. Natural and peaceful.',
    author: 'Vox',
    accent: '#4caf50',
    bg: '#0a1a0a',
    theme: 'custom',
    customColors: {
      bg: '#0a1a0a', bgDim: '#061206', bgLight: '#142614',
      fg: '#c8e6c9', fgDim: '#388e3c', border: '#1b5e20',
      accent: '#4caf50', green: '#66bb6a', red: '#ef5350',
      orange: '#ffb74d', cyan: '#4dd0e1', purple: '#b39ddb',
    },
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    tabBarHeight: 30,
    statusBarHeight: 26,
    titlebarHeight: 2,
    borderRadius: 12,
    transitionSpeed: 200,
    tabOpacity: 0.85,
    ntpLayout: 'zen',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'arctic-ice',
    name: 'Arctic Ice',
    description: 'Frost blue + white. Minimal square tabs. Crisp and clean.',
    author: 'Vox',
    accent: '#81d4fa',
    bg: '#0a1929',
    theme: 'custom',
    customColors: {
      bg: '#0a1929', bgDim: '#061220', bgLight: '#122940',
      fg: '#e3f2fd', fgDim: '#42a5f5', border: '#1565c0',
      accent: '#81d4fa', green: '#80cbc4', red: '#ef5350',
      orange: '#ffb74d', cyan: '#40c4ff', purple: '#b39ddb',
    },
    tabShape: 'square',
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'candy-pop',
    name: 'Candy Pop',
    description: 'Bright playful colors. Rounded tabs. Fun and energetic.',
    author: 'Vox',
    accent: '#ff4081',
    bg: '#1a1024',
    theme: 'custom',
    customColors: {
      bg: '#1a1024', bgDim: '#120a1a', bgLight: '#261836',
      fg: '#f3e5f5', fgDim: '#9c27b0', border: '#3d1f56',
      accent: '#ff4081', green: '#69f0ae', red: '#ff5252',
      orange: '#ffab40', cyan: '#18ffff', purple: '#ea80fc',
    },
    tabShape: 'pill',
    fontFamily: "'Nunito', 'Segoe UI', sans-serif",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 12,
    transitionSpeed: 180,
    tabOpacity: 0.95,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'top',
    sidebarPosition: 'left',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    description: 'Classic Monokai colors. Yandex tabs. Editor-grade contrast.',
    author: 'Vox',
    accent: '#fc9618',
    bg: '#2d2a2e',
    theme: 'custom',
    customColors: {
      bg: '#2d2a2e', bgDim: '#221f22', bgLight: '#403e41',
      fg: '#fcfcfa', fgDim: '#727072', border: '#5b595c',
      accent: '#fc9618', green: '#a9dc76', red: '#ff6188',
      orange: '#fc9618', cyan: '#78dce8', purple: '#ab9df2',
    },
    tabShape: 'yandex',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 4,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── SUPER DESIGN ─────────────────────────────────
  {
    id: 'neon-aurora',
    name: 'Neon Aurora',
    description: 'Northern lights glow. Glassmorphism everywhere. Trapezoid tabs at bottom.',
    author: 'Vox',
    accent: '#00ffa3',
    bg: '#0a0e14',
    theme: 'custom',
    customColors: {
      bg: '#0a0e14', bgDim: '#060a10', bgLight: '#121a24',
      fg: '#e0e6ed', fgDim: '#4a5568', border: '#1a2432',
      accent: '#00ffa3', green: '#00ffa3', red: '#ff4d6a',
      orange: '#ffaa00', cyan: '#00d4ff', purple: '#b44dff',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Fira Code', 'JetBrains Mono', monospace",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 30,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 180,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 360,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'void-glass',
    name: 'Void Glass',
    description: 'Pure void with glass panels. Ultra-clean. Pill tabs, top status bar.',
    author: 'Vox',
    accent: '#6366f1',
    bg: '#09090b',
    theme: 'custom',
    customColors: {
      bg: '#09090b', bgDim: '#050506', bgLight: '#131316',
      fg: '#fafafa', fgDim: '#52525b', border: '#1c1c1f',
      accent: '#6366f1', green: '#22c55e', red: '#ef4444',
      orange: '#f59e0b', cyan: '#06b6d4', purple: '#a855f7',
    },
    tabShape: 'pill',
    fontFamily: "'Inter', 'SF Pro', system-ui, sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 2,
    borderRadius: 10,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'top',
    sidebarPosition: 'right',
    sidebarWidth: 380,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'ember-forge',
    name: 'Ember Forge',
    description: 'Volcanic forge. Deep ember glow on black. Trapezoid tabs. Industrial feel.',
    author: 'Vox',
    accent: '#ff4500',
    bg: '#0c0604',
    theme: 'custom',
    customColors: {
      bg: '#0c0604', bgDim: '#080403', bgLight: '#1a0e0a',
      fg: '#f5e6d3', fgDim: '#8b6f5e', border: '#2a1a12',
      accent: '#ff4500', green: '#4ade80', red: '#ef4444',
      orange: '#fb923c', cyan: '#22d3ee', purple: '#c084fc',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', 'Fira Code', monospace",
    fontSize: 14,
    tabBarHeight: 40,
    statusBarHeight: 30,
    titlebarHeight: 8,
    borderRadius: 1,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 360,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'crystal-ice',
    name: 'Crystal Ice',
    description: 'Frozen crystal. Icy blue on near-white. Glassmorphism sidebar. Clean sharp.',
    author: 'Vox',
    accent: '#38bdf8',
    bg: '#f0f4f8',
    theme: 'custom',
    customColors: {
      bg: '#f0f4f8', bgDim: '#e2e8f0', bgLight: '#ffffff',
      fg: '#0f172a', fgDim: '#64748b', border: '#cbd5e1',
      accent: '#38bdf8', green: '#22c55e', red: '#ef4444',
      orange: '#f59e0b', cyan: '#06b6d4', purple: '#a855f7',
    },
    tabShape: 'rounded',
    fontFamily: "'SF Pro', 'Inter', system-ui, sans-serif",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 26,
    titlebarHeight: 2,
    borderRadius: 8,
    transitionSpeed: 180,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'sakura-dream',
    name: 'Sakura Dream',
    description: 'Cherry blossom pink. Soft rounded tabs. Japanese zen aesthetic. Warm glow.',
    author: 'Vox',
    accent: '#f472b6',
    bg: '#1a0f14',
    theme: 'custom',
    customColors: {
      bg: '#1a0f14', bgDim: '#130a0e', bgLight: '#281620',
      fg: '#fce7f3', fgDim: '#9d6b88', border: '#3d2030',
      accent: '#f472b6', green: '#86efac', red: '#fb7185',
      orange: '#fbbf24', cyan: '#67e8f9', purple: '#e879f9',
    },
    tabShape: 'rounded',
    fontFamily: "'Zen Kaku Gothic New', 'Noto Sans JP', sans-serif",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 26,
    titlebarHeight: 2,
    borderRadius: 10,
    transitionSpeed: 250,
    tabOpacity: 0.9,
    ntpLayout: 'zen',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 320,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'hacker-matrix',
    name: 'Hacker Matrix',
    description: 'Full matrix vibe. Green on pure black. Square tabs. Terminal aesthetic.',
    author: 'Vox',
    accent: '#00ff41',
    bg: '#000000',
    theme: 'custom',
    customColors: {
      bg: '#000000', bgDim: '#000000', bgLight: '#0a1a0a',
      fg: '#00ff41', fgDim: '#006618', border: '#003300',
      accent: '#00ff41', green: '#00ff41', red: '#ff0000',
      orange: '#ff8800', cyan: '#00ffff', purple: '#00ff88',
    },
    tabShape: 'square',
    fontFamily: "'Share Tech Mono', 'Courier New', monospace",
    fontSize: 13,
    tabBarHeight: 28,
    statusBarHeight: 22,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 50,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'bottom',
    statusBarPosition: 'top',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'aurora-pink',
    name: 'Aurora Pink',
    description: 'Neon pink aurora on midnight. Trapezoid bottom tabs. Electric and bold.',
    author: 'Vox',
    accent: '#ff2d7b',
    bg: '#0a0610',
    theme: 'custom',
    customColors: {
      bg: '#0a0610', bgDim: '#06040a', bgLight: '#150c1e',
      fg: '#f0e0f5', fgDim: '#7a5090', border: '#2a1540',
      accent: '#ff2d7b', green: '#4ade80', red: '#ff1744',
      orange: '#ff9100', cyan: '#00e5ff', purple: '#d946ef',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Fira Code', 'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 140,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'obsidian-elite',
    name: 'Obsidian Elite',
    description: 'Premium obsidian. Deep warm black, gold accent. Rounded tabs. Luxury feel.',
    author: 'Vox',
    accent: '#d4a574',
    bg: '#0c0a08',
    theme: 'custom',
    customColors: {
      bg: '#0c0a08', bgDim: '#080605', bgLight: '#1a1510',
      fg: '#e8ddd0', fgDim: '#8a7e70', border: '#2a2420',
      accent: '#d4a574', green: '#a3d977', red: '#e85d5d',
      orange: '#e8a04c', cyan: '#7ac5c5', purple: '#b890d4',
    },
    tabShape: 'rounded',
    fontFamily: "'DM Sans', 'SF Pro', system-ui, sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 200,
    tabOpacity: 0.95,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 360,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'cyber-violet',
    name: 'Cyber Violet',
    description: 'Deep violet cyberpunk. Neon purple glow on dark. Wave tabs. Futuristic.',
    author: 'Vox',
    accent: '#8b5cf6',
    bg: '#0d0816',
    theme: 'custom',
    customColors: {
      bg: '#0d0816', bgDim: '#080510', bgLight: '#18102a',
      fg: '#e8e0f5', fgDim: '#6a5090', border: '#251a3d',
      accent: '#8b5cf6', green: '#34d399', red: '#f87171',
      orange: '#fbbf24', cyan: '#22d3ee', purple: '#a78bfa',
    },
    tabShape: 'wave',
    fontFamily: "'Space Grotesk', 'Inter', sans-serif",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 4,
    transitionSpeed: 160,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'minimal-white',
    name: 'Minimal White',
    description: 'Ultra clean white. Almost no borders. Pill tabs. Maximum content space.',
    author: 'Vox',
    accent: '#18181b',
    bg: '#fafafa',
    theme: 'custom',
    customColors: {
      bg: '#fafafa', bgDim: '#f4f4f5', bgLight: '#ffffff',
      fg: '#18181b', fgDim: '#a1a1aa', border: '#e4e4e7',
      accent: '#18181b', green: '#16a34a', red: '#dc2626',
      orange: '#ea580c', cyan: '#0891b2', purple: '#9333ea',
    },
    tabShape: 'pill',
    fontFamily: "'Inter', 'SF Pro', system-ui, sans-serif",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 24,
    titlebarHeight: 0,
    borderRadius: 8,
    transitionSpeed: 200,
    tabOpacity: 0.85,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
]

export function applyPreset(preset: UIPreset, setSettings: (p: any) => void) {
  setSettings({
    theme: preset.theme,
    customColors: preset.customColors,
    tabShape: preset.tabShape,
    fontFamily: preset.fontFamily,
    fontSize: preset.fontSize,
    tabBarHeight: preset.tabBarHeight,
    statusBarHeight: preset.statusBarHeight,
    titlebarHeight: preset.titlebarHeight,
    borderRadius: preset.borderRadius,
    transitionSpeed: preset.transitionSpeed,
    tabOpacity: preset.tabOpacity,
    ntpLayout: preset.ntpLayout,
    tabBarPosition: preset.tabBarPosition,
    statusBarPosition: preset.statusBarPosition,
    sidebarPosition: preset.sidebarPosition,
    sidebarWidth: preset.sidebarWidth,
    workspacePosition: preset.workspacePosition,
    showTabBar: preset.showTabBar,
    showStatusBar: preset.showStatusBar,
    workspaceShow: preset.workspaceShow,
    zenMode: preset.zenMode,
    currentPreset: preset.id,
  })
}
