import type { ThemePreset, ThemeColors } from './types'

export type LayoutPosition = 'top' | 'bottom'
export type SidebarSide = 'left' | 'right'

export interface UIPreset {
  id: string
  name: string
  description: string
  author: string
  accent: string
  bg: string
  theme: ThemePreset
  customColors?: ThemeColors
  tabShape: 'square' | 'rounded' | 'pill' | 'trapezoid' | 'yandex' | 'wave'
  fontFamily: string
  fontSize: number
  tabBarHeight: number
  statusBarHeight: number
  titlebarHeight: number
  borderRadius: number
  transitionSpeed: number
  tabOpacity: number
  ntpLayout: 'default' | 'minimal' | 'centered' | 'zen' | 'gradient'
  tabBarPosition: LayoutPosition
  statusBarPosition: LayoutPosition
  sidebarPosition: SidebarSide
  sidebarWidth: number
  workspacePosition: 'top' | 'bottom'
  showTabBar: boolean
  showStatusBar: boolean
  workspaceShow: boolean
  zenMode: boolean
}

export const BUILT_IN_PRESETS: UIPreset[] = [
  // ─── Classic ──────────────────────────────────────
  {
    id: 'vox-classic',
    name: 'Vox Classic',
    description: 'The default. Tokyo Night, rounded tabs, balanced.',
    author: 'Vox',
    accent: '#7aa2f7',
    bg: '#1a1b26',
    theme: 'tokyo-night',
    tabShape: 'rounded',
    fontFamily: "'Consolas', 'SF Mono', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'vox-classic-dark',
    name: 'Vox Classic Dark',
    description: 'Same layout, deeper colors. Gruvbox warmth.',
    author: 'Vox',
    accent: '#458588',
    bg: '#282828',
    theme: 'gruvbox',
    tabShape: 'rounded',
    fontFamily: "'Consolas', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Zen / Minimal ────────────────────────────────
  {
    id: 'zen-minimal',
    name: 'Zen Minimal',
    description: 'Nord. Pill tabs. No status bar. Centered NTP.',
    author: 'Vox',
    accent: '#88c0d0',
    bg: '#2e3440',
    theme: 'nord',
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    tabBarHeight: 30,
    statusBarHeight: 24,
    titlebarHeight: 2,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 0.85,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'midnight-zen',
    name: 'Midnight Zen',
    description: 'Full zen mode. Sidebar tabs, gradient NTP, nothing else.',
    author: 'Vox',
    accent: '#bb9af7',
    bg: '#1a1b26',
    theme: 'tokyo-night',
    tabShape: 'rounded',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 0,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 280,
    workspacePosition: 'top',
    showTabBar: false,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: true,
  },
  {
    id: 'ultra-minimal',
    name: 'Ultra Minimal',
    description: 'Almost nothing visible. 2px titlebar, tiny tabs, right sidebar.',
    author: 'Vox',
    accent: '#565f89',
    bg: '#16161e',
    theme: 'custom',
    customColors: {
      bg: '#16161e', bgDim: '#111119', bgLight: '#1e1e2e',
      fg: '#a9b1d6', fgDim: '#444b6a', border: '#1e1e2e',
      accent: '#565f89', green: '#9ece6a', red: '#f7768e',
      orange: '#ff9e64', cyan: '#7dcfff', purple: '#bb9af7',
    },
    tabShape: 'pill',
    fontFamily: "system-ui, sans-serif",
    fontSize: 12,
    tabBarHeight: 26,
    statusBarHeight: 20,
    titlebarHeight: 2,
    borderRadius: 10,
    transitionSpeed: 300,
    tabOpacity: 0.7,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 260,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'flatland',
    name: 'Flatland',
    description: 'Completely flat. No border radius. Tabs at bottom, sidebar right.',
    author: 'Vox',
    accent: '#88c0d0',
    bg: '#2e3440',
    theme: 'nord',
    tabShape: 'square',
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Browser clones ───────────────────────────────
  {
    id: 'chrome-cloned',
    name: 'Chrome Style',
    description: 'Looks like Chrome. Tabs on top, blue accent, centered NTP.',
    author: 'Vox',
    accent: '#4285f4',
    bg: '#202124',
    theme: 'custom',
    customColors: {
      bg: '#202124', bgDim: '#17181a', bgLight: '#292a2d',
      fg: '#e8eaed', fgDim: '#9aa0a6', border: '#3c4043',
      accent: '#4285f4', green: '#34a853', red: '#ea4335',
      orange: '#fbbc04', cyan: '#00bcd4', purple: '#a142f4',
    },
    tabShape: 'rounded',
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 24,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'firefox-cloned',
    name: 'Firefox Style',
    description: 'Firefox Proton look. Tabs on top, orange accent.',
    author: 'Vox',
    accent: '#ff7139',
    bg: '#1c1b22',
    theme: 'custom',
    customColors: {
      bg: '#1c1b22', bgDim: '#15141a', bgLight: '#2b2a33',
      fg: '#fbfbfe', fgDim: '#8f8f9d', border: '#3b3a44',
      accent: '#ff7139', green: '#058b00', red: '#ff4f5e',
      orange: '#ff9f00', cyan: '#00c8ff', purple: '#bf5af2',
    },
    tabShape: 'square',
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'edge-cloned',
    name: 'Edge Style',
    description: 'Microsoft Edge. Tabs on top, cool blue-grey.',
    author: 'Vox',
    accent: '#0078d4',
    bg: '#1f1f1f',
    theme: 'custom',
    customColors: {
      bg: '#1f1f1f', bgDim: '#161616', bgLight: '#2d2d2d',
      fg: '#ffffff', fgDim: '#999999', border: '#404040',
      accent: '#0078d4', green: '#16c60c', red: '#e81123',
      orange: '#f7630c', cyan: '#00b7c3', purple: '#8764b8',
    },
    tabShape: 'pill',
    fontFamily: "system-ui, 'Segoe UI', sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 26,
    titlebarHeight: 6,
    borderRadius: 8,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'opera-cloned',
    name: 'Opera Style',
    description: 'Opera GX vibes. Tabs top, red-black, sidebar right.',
    author: 'Vox',
    accent: '#ff1b2d',
    bg: '#121212',
    theme: 'custom',
    customColors: {
      bg: '#121212', bgDim: '#0a0a0a', bgLight: '#1e1e1e',
      fg: '#ffffff', fgDim: '#7a7a7a', border: '#2a2a2a',
      accent: '#ff1b2d', green: '#00e676', red: '#ff1744',
      orange: '#ff9100', cyan: '#00e5ff', purple: '#d500f9',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Consolas', monospace",
    fontSize: 13,
    tabBarHeight: 38,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 0,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'yandex-cloned',
    name: 'Yandex Style',
    description: 'Yandex Browser. Tabs on top, bright accent.',
    author: 'Vox',
    accent: '#fc3f1d',
    bg: '#191919',
    theme: 'custom',
    customColors: {
      bg: '#191919', bgDim: '#111111', bgLight: '#262626',
      fg: '#ffffff', fgDim: '#999999', border: '#333333',
      accent: '#fc3f1d', green: '#3fcc2f', red: '#ff3333',
      orange: '#ff9900', cyan: '#33ccff', purple: '#9966ff',
    },
    tabShape: 'yandex',
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 4,
    borderRadius: 3,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'arc-cloned',
    name: 'Arc Style',
    description: 'Arc Browser look. Sidebar tabs, no tab bar, pill shapes.',
    author: 'Vox',
    accent: '#6e56cf',
    bg: '#1a1a2e',
    theme: 'custom',
    customColors: {
      bg: '#1a1a2e', bgDim: '#12121f', bgLight: '#252540',
      fg: '#e0def4', fgDim: '#6e6e8a', border: '#2a2a45',
      accent: '#6e56cf', green: '#56d364', red: '#f85149',
      orange: '#d29922', cyan: '#39c5cf', purple: '#bc8cff',
    },
    tabShape: 'pill',
    fontFamily: "'SF Mono', 'Fira Code', monospace",
    fontSize: 12,
    tabBarHeight: 32,
    statusBarHeight: 0,
    titlebarHeight: 0,
    borderRadius: 12,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 280,
    workspacePosition: 'top',
    showTabBar: false,
    showStatusBar: false,
    workspaceShow: true,
    zenMode: true,
  },

  // ─── Color themes ─────────────────────────────────
  {
    id: 'dracula-vampire',
    name: 'Dracula Vampire',
    description: 'Dark dramatic. Dracula + trapezoid tabs. Workspaces at bottom.',
    author: 'Vox',
    accent: '#bd93f9',
    bg: '#282a36',
    theme: 'dracula',
    tabShape: 'trapezoid',
    fontFamily: "'Cascadia Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'solarized-ink',
    name: 'Solarized Ink',
    description: 'Warm Solarized Dark. Wave tabs. Sidebar right.',
    author: 'Vox',
    accent: '#268bd2',
    bg: '#002b36',
    theme: 'solarized',
    tabShape: 'wave',
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 15,
    tabBarHeight: 38,
    statusBarHeight: 30,
    titlebarHeight: 8,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 360,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'catppuccin-dream',
    name: 'Catppuccin Dream',
    description: 'Soft pastels. Catppuccin Mocha. Smooth & gentle.',
    author: 'Vox',
    accent: '#89b4fa',
    bg: '#1e1e2e',
    theme: 'catppuccin',
    tabShape: 'pill',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 250,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    description: 'Monokai. Square tabs. Tabs at bottom. Retro coder.',
    author: 'Vox',
    accent: '#a6e22e',
    bg: '#272822',
    theme: 'monokai',
    tabShape: 'square',
    fontFamily: "'Consolas', monospace",
    fontSize: 14,
    tabBarHeight: 36,
    statusBarHeight: 30,
    titlebarHeight: 10,
    borderRadius: 0,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'ayu-mirage',
    name: 'Ayu Mirage',
    description: 'Sleek Ayu Dark. Rounded tabs. Centered NTP.',
    author: 'Vox',
    accent: '#36a3d9',
    bg: '#0f1419',
    theme: 'ayu',
    tabShape: 'rounded',
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 5,
    transitionSpeed: 180,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'one-dark-atom',
    name: 'One Dark Atom',
    description: 'Atom editor vibes. One Dark. Wave tabs at bottom.',
    author: 'Vox',
    accent: '#61afef',
    bg: '#282c34',
    theme: 'one-dark',
    tabShape: 'wave',
    fontFamily: "'Fira Code', 'Source Code Pro', monospace",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Light themes ─────────────────────────────────
  {
    id: 'github-coder',
    name: 'GitHub Coder',
    description: 'GitHub Light. Tabs on top. Clean daytime coding.',
    author: 'Vox',
    accent: '#0969da',
    bg: '#ffffff',
    theme: 'github-light',
    tabShape: 'square',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    tabBarHeight: 30,
    statusBarHeight: 24,
    titlebarHeight: 2,
    borderRadius: 2,
    transitionSpeed: 100,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'latte-latte',
    name: 'Catppuccin Latte',
    description: 'Soft light. Catppuccin Latte. Tabs on top.',
    author: 'Vox',
    accent: '#1e66f5',
    bg: '#eff1f5',
    theme: 'catppuccin-latte',
    tabShape: 'pill',
    fontFamily: "'SF Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 8,
    transitionSpeed: 200,
    tabOpacity: 0.9,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'tokyo-day',
    name: 'Tokyo Day',
    description: 'Tokyo Day light theme. Tabs on top. Clean & modern.',
    author: 'Vox',
    accent: '#2e7de9',
    bg: '#e1e2e7',
    theme: 'tokyo-day',
    tabShape: 'rounded',
    fontFamily: "system-ui, sans-serif",
    fontSize: 13,
    tabBarHeight: 34,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 6,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    description: 'Solarized Light. Wave tabs. Sidebar right.',
    author: 'Vox',
    accent: '#268bd2',
    bg: '#fdf6e3',
    theme: 'solarized-light',
    tabShape: 'wave',
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 14,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 4,
    transitionSpeed: 180,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'nord-light',
    name: 'Nord Light',
    description: 'Nord Light. Tabs on top. Clean, calm, readable.',
    author: 'Vox',
    accent: '#5e81ac',
    bg: '#eceff4',
    theme: 'nord-light',
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 320,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },

  // ─── Extreme / Experimental ───────────────────────
  {
    id: 'terminal-green',
    name: 'Terminal Green',
    description: 'Matrix vibes. Green on black. Tabs bottom, sidebar right.',
    author: 'Vox',
    accent: '#00ff41',
    bg: '#0d0208',
    theme: 'custom',
    customColors: {
      bg: '#0d0208', bgDim: '#000000', bgLight: '#003b00',
      fg: '#00ff41', fgDim: '#007a1c', border: '#003b00',
      accent: '#00ff41', green: '#00ff41', red: '#ff0000',
      orange: '#ff8c00', cyan: '#00ffff', purple: '#ff00ff',
    },
    tabShape: 'square',
    fontFamily: "'Consolas', 'Courier New', monospace",
    fontSize: 13,
    tabBarHeight: 28,
    statusBarHeight: 22,
    titlebarHeight: 0,
    borderRadius: 0,
    transitionSpeed: 50,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'bottom',
    statusBarPosition: 'top',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'synthwave-neon',
    name: 'Synthwave Neon',
    description: 'Retro-futuristic. Tabs bottom. Neon pink/cyan, sidebar right.',
    author: 'Vox',
    accent: '#f72585',
    bg: '#0f0e17',
    theme: 'custom',
    customColors: {
      bg: '#0f0e17', bgDim: '#08070d', bgLight: '#1a1928',
      fg: '#fffffe', fgDim: '#72757e', border: '#2e2d3d',
      accent: '#f72585', green: '#4cc9f0', red: '#ff006e',
      orange: '#fb5607', cyan: '#4cc9f0', purple: '#7209b7',
    },
    tabShape: 'trapezoid',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 2,
    transitionSpeed: 120,
    tabOpacity: 1,
    ntpLayout: 'gradient',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'rose-pine',
    name: 'Rose Pine',
    description: 'Rose Pine palette. Soft & muted. Pill tabs on top.',
    author: 'Vox',
    accent: '#c4a7e7',
    bg: '#191724',
    theme: 'custom',
    customColors: {
      bg: '#191724', bgDim: '#111019', bgLight: '#26233a',
      fg: '#e0def4', fgDim: '#6e6a86', border: '#26233a',
      accent: '#c4a7e7', green: '#9ccfd8', red: '#eb6f92',
      orange: '#ea9a97', cyan: '#9ccfd8', purple: '#c4a7e7',
    },
    tabShape: 'pill',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 32,
    statusBarHeight: 26,
    titlebarHeight: 4,
    borderRadius: 10,
    transitionSpeed: 250,
    tabOpacity: 0.9,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'nord-dark-max',
    name: 'Nord Max',
    description: 'Nord Dark, maximum size. Large font, tall bars.',
    author: 'Vox',
    accent: '#88c0d0',
    bg: '#2e3440',
    theme: 'nord',
    tabShape: 'square',
    fontFamily: "'Consolas', monospace",
    fontSize: 16,
    tabBarHeight: 44,
    statusBarHeight: 34,
    titlebarHeight: 12,
    borderRadius: 6,
    transitionSpeed: 200,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 360,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'compact-rocket',
    name: 'Compact Rocket',
    description: 'Tiny & fast. 24px tabs, compact sidebar.',
    author: 'Vox',
    accent: '#7dcfff',
    bg: '#1a1b26',
    theme: 'tokyo-night',
    tabShape: 'pill',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    tabBarHeight: 24,
    statusBarHeight: 20,
    titlebarHeight: 2,
    borderRadius: 4,
    transitionSpeed: 80,
    tabOpacity: 1,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 280,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'gruvbox-retro',
    name: 'Gruvbox Retro',
    description: 'Gruvbox warmth. Tabs bottom. Sidebar right. Zero radius.',
    author: 'Vox',
    accent: '#d79921',
    bg: '#282828',
    theme: 'gruvbox',
    tabShape: 'square',
    fontFamily: "'Consolas', monospace",
    fontSize: 14,
    tabBarHeight: 36,
    statusBarHeight: 30,
    titlebarHeight: 10,
    borderRadius: 0,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'default',
    tabBarPosition: 'bottom',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 340,
    workspacePosition: 'bottom',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
  {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    description: 'Very dark blue. Tabs top. Sidebar right. Max immersion.',
    author: 'Vox',
    accent: '#3b4252',
    bg: '#0b0e14',
    theme: 'custom',
    customColors: {
      bg: '#0b0e14', bgDim: '#060810', bgLight: '#141820',
      fg: '#8892b0', fgDim: '#2e3450', border: '#141820',
      accent: '#64ffda', green: '#64ffda', red: '#ff5370',
      orange: '#f78c6c', cyan: '#89ddff', purple: '#c792ea',
    },
    tabShape: 'rounded',
    fontFamily: "'Fira Code', monospace",
    fontSize: 13,
    tabBarHeight: 30,
    statusBarHeight: 22,
    titlebarHeight: 2,
    borderRadius: 3,
    transitionSpeed: 300,
    tabOpacity: 0.8,
    ntpLayout: 'minimal',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'right',
    sidebarWidth: 300,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: false,
    workspaceShow: false,
    zenMode: false,
  },
  {
    id: 'material-dark',
    name: 'Material Dark',
    description: 'Google Material Design. Tabs top. Blue accent.',
    author: 'Vox',
    accent: '#82b1ff',
    bg: '#263238',
    theme: 'custom',
    customColors: {
      bg: '#263238', bgDim: '#1c2529', bgLight: '#37474f',
      fg: '#eeffff', fgDim: '#546e7a', border: '#37474f',
      accent: '#82b1ff', green: '#c3e88d', red: '#ff5370',
      orange: '#f78c6c', cyan: '#89ddff', purple: '#c792ea',
    },
    tabShape: 'rounded',
    fontFamily: "'Roboto Mono', monospace",
    fontSize: 13,
    tabBarHeight: 36,
    statusBarHeight: 28,
    titlebarHeight: 6,
    borderRadius: 6,
    transitionSpeed: 150,
    tabOpacity: 1,
    ntpLayout: 'centered',
    tabBarPosition: 'top',
    statusBarPosition: 'bottom',
    sidebarPosition: 'left',
    sidebarWidth: 340,
    workspacePosition: 'top',
    showTabBar: true,
    showStatusBar: true,
    workspaceShow: true,
    zenMode: false,
  },
]

export function applyPreset(preset: UIPreset, setSettings: (p: any) => void) {
  setSettings({
    theme: preset.theme,
    customColors: preset.customColors,
    tabShape: preset.tabShape,
    fontFamily: preset.fontFamily,
    fontSize: preset.fontSize,
    tabBarHeight: preset.tabBarHeight,
    statusBarHeight: preset.statusBarHeight,
    titlebarHeight: preset.titlebarHeight,
    borderRadius: preset.borderRadius,
    transitionSpeed: preset.transitionSpeed,
    tabOpacity: preset.tabOpacity,
    ntpLayout: preset.ntpLayout,
    tabBarPosition: preset.tabBarPosition,
    statusBarPosition: preset.statusBarPosition,
    sidebarPosition: preset.sidebarPosition,
    sidebarWidth: preset.sidebarWidth,
    workspacePosition: preset.workspacePosition,
    showTabBar: preset.showTabBar,
    showStatusBar: preset.showStatusBar,
    workspaceShow: preset.workspaceShow,
    zenMode: preset.zenMode,
    currentPreset: preset.id,
  })
}
